project:
  type: website
  output-dir: _site
  preview:
    port: 5550
    browser: false
    watch-inputs: true
    navigate: false

website:
  title: ""
  search:
    location: navbar
  reader-mode: false
  back-to-top-navigation: true
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - slides/index.qmd
  page-footer:
    left: "© 2025 Daniel Bekele, Gregory M. Kapfhammer, Jaclyn Pham"
    right:
      - text: "{{< iconify fa github size=18px >}}"
        href: https://www.gregorykapfhammer.com/

format:
  html:
    mainfont: Inter
    monofont: Ubuntu Mono
    fontsize: 1.25em
    theme: zephyr
    highlight-style: github
    css: css/styles.css

execute:
  freeze: auto 
